import {
  DailyMissionConfig,
  DailyWheelRewardConfig,
} from 'src/app/models/daily-events.model';

const DAILY_MISSION_REWARD_COINS = 2;
const VIDEO_MISSION_REWARD_COINS = 3;

const ADS_MISSION: DailyMissionConfig = {
  id: 'watch_3_ads',
  title: 'Sponsor del giorno',
  description: 'Guarda 3 video premio.',
  metric: 'adsWatched',
  target: 3,
  rewardCoins: VIDEO_MISSION_REWARD_COINS,
};

/*
 * I piani sono 7: uno per ogni giorno della settimana. La missione pubblicita
 * vale 3 TurtleCoins, mentre tutte le altre valgono 2: completarle tutte
 * porta a 15 TurtleCoins extra, oltre ai 25 del minigioco daily.
 */
export const DAILY_MISSION_PLANS: DailyMissionConfig[][] = [
  [
    ADS_MISSION,
    {
      id: 'mon_check_daily_reward',
      title: 'Bussola premi',
      description: 'Apri la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_spin_wheel',
      title: 'Giro fortunato',
      description: 'Gira la ruota almeno una volta.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_complete_1_level',
      title: 'Primo passo',
      description: 'Completa 1 livello normale.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_complete_2_levels',
      title: 'Rotta avviata',
      description: 'Completa 2 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_complete_3_levels',
      title: 'Tre colpi',
      description: 'Completa 3 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_complete_5_levels',
      title: 'Passo deciso',
      description: 'Completa 5 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'tue_check_daily_reward',
      title: 'Forziere aperto',
      description: 'Controlla la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_complete_1_level',
      title: 'Sblocco veloce',
      description: 'Completa 1 livello normale.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_complete_3_levels',
      title: 'Ritmo buono',
      description: 'Completa 3 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_spin_wheel',
      title: 'Giro rituale',
      description: 'Gira la ruota della fortuna.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_complete_4_levels',
      title: 'Allenamento',
      description: 'Completa 4 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_complete_6_levels',
      title: 'Serie lunga',
      description: 'Completa 6 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 6,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'wed_check_daily_reward',
      title: 'Passa dal forziere',
      description: 'Controlla il premio giornaliero.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_complete_2_levels',
      title: 'Doppio passo',
      description: 'Completa 2 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_complete_4_levels',
      title: 'Salita costante',
      description: 'Completa 4 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_spin_wheel',
      title: 'Fortuna chiamata',
      description: 'Gira la ruota del giorno.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_complete_5_levels',
      title: 'Cinque conquiste',
      description: 'Completa 5 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_complete_7_levels',
      title: 'Spinta extra',
      description: 'Completa 7 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 7,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'thu_complete_1_level',
      title: 'Entrata pulita',
      description: 'Completa 1 livello normale.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_complete_2_levels',
      title: 'Passo doppio',
      description: 'Completa 2 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_check_daily_reward',
      title: 'Bonus sotto controllo',
      description: 'Apri la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_spin_wheel',
      title: 'Giro rituale',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_complete_5_levels',
      title: 'Buona rotta',
      description: 'Completa 5 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_complete_6_levels',
      title: 'Arrivo al porto',
      description: 'Completa 6 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 6,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'fri_spin_wheel',
      title: 'Ruota del venerdi',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_complete_2_levels',
      title: 'Precisione',
      description: 'Completa 2 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_complete_4_levels',
      title: 'Quattro tap',
      description: 'Completa 4 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_check_daily_reward',
      title: 'Occhio al bonus',
      description: 'Controlla il daily reward.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_complete_5_levels',
      title: 'Venerdi brillante',
      description: 'Completa 5 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_complete_7_levels',
      title: 'Chiusura pulita',
      description: 'Completa 7 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 7,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'sat_complete_1_level',
      title: 'Partenza sprint',
      description: 'Completa 1 livello normale.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_complete_3_levels',
      title: 'Sabato brillante',
      description: 'Completa 3 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_check_daily_reward',
      title: 'Forziere quotidiano',
      description: 'Controlla la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_complete_5_levels',
      title: 'Ritmo weekend',
      description: 'Completa 5 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_spin_wheel',
      title: 'Colpo di fortuna',
      description: 'Gira la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_complete_8_levels',
      title: 'Weekend completato',
      description: 'Completa 8 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 8,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'sun_complete_1_level',
      title: 'Domenica easy',
      description: 'Completa 1 livello normale.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_complete_2_levels',
      title: 'Quattro sicure',
      description: 'Completa 2 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_check_daily_reward',
      title: 'Promemoria premio',
      description: 'Controlla se hai riscosso il daily.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_spin_wheel',
      title: 'Giro relax',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_complete_4_levels',
      title: 'Gran finale',
      description: 'Completa 4 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_complete_6_levels',
      title: 'Settimana chiusa',
      description: 'Completa 6 livelli normali.',
      metric: 'normalLevelsCompleted',
      target: 6,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
];

export const DAILY_MISSION_SWITCH_POOL: DailyMissionConfig[] = [
  {
    id: 'switch_check_daily_reward',
    title: 'Controllo bonus',
    description: 'Apri la reward giornaliera.',
    metric: 'dailyRewardChecks',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_spin_wheel',
    title: 'Giro di prova',
    description: 'Gira la ruota della fortuna.',
    metric: 'wheelSpins',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_1_level',
    title: 'Un livello',
    description: 'Completa 1 livello normale.',
    metric: 'normalLevelsCompleted',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_2_levels',
    title: 'Due livelli',
    description: 'Completa 2 livelli normali.',
    metric: 'normalLevelsCompleted',
    target: 2,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_3_levels',
    title: 'Tre livelli',
    description: 'Completa 3 livelli normali.',
    metric: 'normalLevelsCompleted',
    target: 3,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_4_levels',
    title: 'Quattro livelli',
    description: 'Completa 4 livelli normali.',
    metric: 'normalLevelsCompleted',
    target: 4,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_5_levels',
    title: 'Cinque livelli',
    description: 'Completa 5 livelli normali.',
    metric: 'normalLevelsCompleted',
    target: 5,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_7_levels',
    title: 'Sette livelli',
    description: 'Completa 7 livelli normali.',
    metric: 'normalLevelsCompleted',
    target: 7,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
];

export const DAILY_WHEEL_REWARDS: DailyWheelRewardConfig[] = [
  {
    id: 'coins_3',
    label: '+3 TurtleCoins',
    shortLabel: '+3',
    type: 'coins',
    amount: 3,
    weight: 22,
  },
  {
    id: 'coins_5',
    label: '+5 TurtleCoins',
    shortLabel: '+5',
    type: 'coins',
    amount: 5,
    weight: 18,
  },
  {
    id: 'xp_10',
    label: '+10 XP',
    shortLabel: '+10 XP',
    type: 'xp',
    amount: 10,
    weight: 18,
  },
  {
    id: 'coins_8',
    label: '+8 TurtleCoins',
    shortLabel: '+8',
    type: 'coins',
    amount: 8,
    weight: 14,
  },
  {
    id: 'base_avatar',
    label: 'Avatar base',
    shortLabel: 'Avatar',
    type: 'baseAvatar',
    weight: 8,
  },
  {
    id: 'coins_10',
    label: '+10 TurtleCoins',
    shortLabel: '+10',
    type: 'coins',
    amount: 10,
    weight: 10,
  },
  {
    id: 'xp_5',
    label: '+5 XP',
    shortLabel: '+5 XP',
    type: 'xp',
    amount: 5,
    weight: 10,
  },
];

export const DAILY_EVENTS_CONFIG = {
  dailyChallengeQuestionCount: 10,
  dailyChallengeCoinsReward: 25,
};

