import {
  DailyMissionConfig,
  DailyWheelRewardConfig,
} from 'src/app/models/daily-events.model';

const ADS_MISSION: DailyMissionConfig = {
  id: 'watch_3_ads',
  title: 'Sponsor del giorno',
  description: 'Guarda 3 video premio.',
  metric: 'adsWatched',
  target: 3,
  rewardCoins: 10,
};

/*
 * I piani sono 7: uno per ogni giorno della settimana. La missione pubblicita
 * viene inserita sempre in testa, mentre le altre cambiano ritmo e obiettivi.
 */
export const DAILY_MISSION_PLANS: DailyMissionConfig[][] = [
  [
    ADS_MISSION,
    {
      id: 'check_daily_reward',
      title: 'Bussola premi',
      description: 'Apri la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'spin_wheel',
      title: 'Giro fortunato',
      description: 'Gira la ruota almeno una volta.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'start_daily_challenge',
      title: 'Primo tuffo',
      description: 'Inizia la sfida giornaliera.',
      metric: 'dailyChallengeStarted',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'answer_3_daily',
      title: 'Riscaldamento',
      description: 'Rispondi a 3 domande della sfida.',
      metric: 'dailyChallengeQuestions',
      target: 3,
      rewardCoins: 5,
    },
    {
      id: 'correct_5_daily',
      title: 'Mente lucida',
      description: 'Indovina 5 domande nella sfida.',
      metric: 'dailyChallengeCorrect',
      target: 5,
      rewardCoins: 8,
    },
    {
      id: 'complete_daily',
      title: 'Sfida chiusa',
      description: 'Completa tutte le 10 domande daily.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'spin_wheel',
      title: 'Ruota in moto',
      description: 'Fai un giro alla ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'answer_5_daily',
      title: 'Cinquina veloce',
      description: 'Gioca 5 domande daily.',
      metric: 'dailyChallengeQuestions',
      target: 5,
      rewardCoins: 6,
    },
    {
      id: 'use_help_daily',
      title: 'Aiuto tattico',
      description: 'Usa un aiuto nella sfida.',
      metric: 'dailyChallengeHelps',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'correct_6_daily',
      title: 'Ritmo alto',
      description: 'Indovina 6 domande daily.',
      metric: 'dailyChallengeCorrect',
      target: 6,
      rewardCoins: 8,
    },
    {
      id: 'check_daily_reward',
      title: 'Passa dal forziere',
      description: 'Controlla il premio giornaliero.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'complete_daily',
      title: 'Daily completata',
      description: 'Arriva fino alla decima domanda.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'start_daily_challenge',
      title: 'Accendi il quiz',
      description: 'Avvia la sfida daily.',
      metric: 'dailyChallengeStarted',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'correct_3_daily',
      title: 'Tre colpi buoni',
      description: 'Indovina 3 domande.',
      metric: 'dailyChallengeCorrect',
      target: 3,
      rewardCoins: 5,
    },
    {
      id: 'answer_10_daily',
      title: 'Maratona mini',
      description: 'Gioca tutte le 10 domande.',
      metric: 'dailyChallengeQuestions',
      target: 10,
      rewardCoins: 8,
    },
    {
      id: 'spin_wheel',
      title: 'Fortuna chiamata',
      description: 'Gira la ruota del giorno.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'perfect_daily',
      title: 'Quasi leggenda',
      description: 'Chiudi la daily senza errori.',
      metric: 'dailyChallengePerfect',
      target: 1,
      rewardCoins: 15,
    },
    {
      id: 'complete_daily',
      title: 'Sigillo daily',
      description: 'Completa la sfida giornaliera.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'check_daily_reward',
      title: 'Premio sotto controllo',
      description: 'Apri il calendario reward.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'use_2_helps_daily',
      title: 'Stratega',
      description: 'Usa 2 aiuti nella sfida.',
      metric: 'dailyChallengeHelps',
      target: 2,
      rewardCoins: 7,
    },
    {
      id: 'correct_7_daily',
      title: 'Sette risposte',
      description: 'Indovina 7 domande daily.',
      metric: 'dailyChallengeCorrect',
      target: 7,
      rewardCoins: 10,
    },
    {
      id: 'spin_wheel',
      title: 'Giro rituale',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'answer_8_daily',
      title: 'Buona rotta',
      description: 'Gioca almeno 8 domande.',
      metric: 'dailyChallengeQuestions',
      target: 8,
      rewardCoins: 7,
    },
    {
      id: 'complete_daily',
      title: 'Arrivo al porto',
      description: 'Completa la daily.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'spin_wheel',
      title: 'Ruota del venerdi',
      description: 'Prendi il giro gratis.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'no_help_daily',
      title: 'Senza stampelle',
      description: 'Completa la daily senza aiuti.',
      metric: 'dailyChallengeNoHelp',
      target: 1,
      rewardCoins: 15,
    },
    {
      id: 'correct_5_daily',
      title: 'Precisione',
      description: 'Indovina 5 domande.',
      metric: 'dailyChallengeCorrect',
      target: 5,
      rewardCoins: 8,
    },
    {
      id: 'answer_10_daily',
      title: 'Dieci tap',
      description: 'Arriva alla decima domanda.',
      metric: 'dailyChallengeQuestions',
      target: 10,
      rewardCoins: 8,
    },
    {
      id: 'check_daily_reward',
      title: 'Occhio al bonus',
      description: 'Controlla il daily reward.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'complete_daily',
      title: 'Chiusura pulita',
      description: 'Completa la sfida del giorno.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'start_daily_challenge',
      title: 'Partenza sprint',
      description: 'Avvia il minigioco daily.',
      metric: 'dailyChallengeStarted',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'correct_8_daily',
      title: 'Sabato brillante',
      description: 'Indovina 8 domande.',
      metric: 'dailyChallengeCorrect',
      target: 8,
      rewardCoins: 12,
    },
    {
      id: 'use_help_daily',
      title: 'Scelta saggia',
      description: 'Usa un aiuto quando serve.',
      metric: 'dailyChallengeHelps',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'spin_wheel',
      title: 'Colpo di fortuna',
      description: 'Gira la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'check_daily_reward',
      title: 'Forziere quotidiano',
      description: 'Apri la reward giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'complete_daily',
      title: 'Weekend completato',
      description: 'Completa tutte le 10 domande.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'answer_4_daily',
      title: 'Domenica easy',
      description: 'Gioca 4 domande daily.',
      metric: 'dailyChallengeQuestions',
      target: 4,
      rewardCoins: 5,
    },
    {
      id: 'correct_4_daily',
      title: 'Quattro sicure',
      description: 'Indovina 4 domande.',
      metric: 'dailyChallengeCorrect',
      target: 4,
      rewardCoins: 6,
    },
    {
      id: 'spin_wheel',
      title: 'Giro relax',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'check_daily_reward',
      title: 'Promemoria premio',
      description: 'Controlla se hai riscosso il daily.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: 5,
    },
    {
      id: 'correct_7_daily',
      title: 'Gran finale',
      description: 'Indovina 7 domande daily.',
      metric: 'dailyChallengeCorrect',
      target: 7,
      rewardCoins: 10,
    },
    {
      id: 'complete_daily',
      title: 'Settimana chiusa',
      description: 'Completa la sfida giornaliera.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: 12,
    },
  ],
];

export const DAILY_WHEEL_REWARDS: DailyWheelRewardConfig[] = [
  {
    id: 'coins_3',
    label: '+3 TurtleCoins',
    shortLabel: '+3',
    type: 'coins',
    amount: 3,
    weight: 22,
  },
  {
    id: 'coins_5',
    label: '+5 TurtleCoins',
    shortLabel: '+5',
    type: 'coins',
    amount: 5,
    weight: 18,
  },
  {
    id: 'xp_10',
    label: '+10 XP',
    shortLabel: '+10 XP',
    type: 'xp',
    amount: 10,
    weight: 18,
  },
  {
    id: 'coins_8',
    label: '+8 TurtleCoins',
    shortLabel: '+8',
    type: 'coins',
    amount: 8,
    weight: 14,
  },
  {
    id: 'base_avatar',
    label: 'Avatar base',
    shortLabel: 'Avatar',
    type: 'baseAvatar',
    weight: 8,
  },
  {
    id: 'coins_10',
    label: '+10 TurtleCoins',
    shortLabel: '+10',
    type: 'coins',
    amount: 10,
    weight: 10,
  },
  {
    id: 'xp_5',
    label: '+5 XP',
    shortLabel: '+5 XP',
    type: 'xp',
    amount: 5,
    weight: 10,
  },
];

export const DAILY_EVENTS_CONFIG = {
  dailyChallengeQuestionCount: 10,
  dailyChallengeCoinsReward: 25,
};
