import {
  DailyMissionConfig,
  DailyWheelRewardConfig,
} from 'src/app/models/daily-events.model';
import { DifficultyId } from 'src/app/models/difficulty.model';

const DAILY_MISSION_REWARD_COINS = 2;
const VIDEO_MISSION_REWARD_COINS = 3;

const ADS_MISSION: DailyMissionConfig = {
  id: 'watch_3_ads',
  title: 'Sponsor del giorno',
  description: 'Guarda 3 video premio.',
  metric: 'adsWatched',
  target: 3,
  rewardCoins: VIDEO_MISSION_REWARD_COINS,
};

/*
 * Ogni giorno mantiene la missione fissa dei 3 video premio.
 * Le altre 6 missioni cambiano per spingere l'utente a provare quiz normali,
 * ruota, daily reward e sfida giornaliera senza vedere sempre le stesse card.
 */
export const DAILY_MISSION_PLANS: DailyMissionConfig[][] = [
  [
    ADS_MISSION,
    {
      id: 'mon_check_daily_reward',
      title: 'Bussola premi',
      description: 'Apri la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_spin_wheel',
      title: 'Giro fortunato',
      description: 'Gira la ruota almeno una volta.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_play_3_quiz',
      title: 'Riscaldamento',
      description: 'Gioca 3 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_win_1_quiz',
      title: 'Colpo pulito',
      description: 'Vinci 1 livello normale.',
      metric: 'normalQuizWon',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_daily_started',
      title: 'Sfida accesa',
      description: 'Avvia la sfida giornaliera.',
      metric: 'dailyChallengeStarted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'mon_daily_5_correct',
      title: 'Fuoco rapido',
      description: 'Rispondi correttamente a 5 domande della sfida.',
      metric: 'dailyChallengeCorrect',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'tue_play_4_quiz',
      title: 'Ritmo buono',
      description: 'Gioca 4 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_win_2_quiz',
      title: 'Doppio centro',
      description: 'Vinci 2 livelli normali.',
      metric: 'normalQuizWon',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_spin_wheel',
      title: 'Giro rituale',
      description: 'Gira la ruota della fortuna.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_use_1_help',
      title: 'Aiuto tattico',
      description: 'Usa 1 aiuto in un livello normale.',
      metric: 'normalHelpsUsed',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_complete_1_level',
      title: 'Nuova conquista',
      description: 'Completa 1 livello non ancora finito.',
      metric: 'normalLevelsCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'tue_daily_completed',
      title: 'Sfida chiusa',
      description: 'Completa la sfida giornaliera.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'wed_check_daily_reward',
      title: 'Passa dal forziere',
      description: 'Controlla il premio giornaliero.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_play_5_quiz',
      title: 'Doppio passo',
      description: 'Gioca 5 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_spin_wheel',
      title: 'Fortuna chiamata',
      description: 'Gira la ruota del giorno.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_use_2_helps',
      title: 'Stratega daily',
      description: 'Usa 2 aiuti nei livelli normali.',
      metric: 'normalHelpsUsed',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_daily_8_questions',
      title: 'Dentro la sfida',
      description: 'Gioca 8 domande nella sfida giornaliera.',
      metric: 'dailyChallengeQuestions',
      target: 8,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'wed_daily_no_help',
      title: 'Senza salvagente',
      description: 'Completa la sfida giornaliera senza aiuti.',
      metric: 'dailyChallengeNoHelp',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'thu_daily_started',
      title: 'Accendi la sfida',
      description: 'Avvia la sfida giornaliera.',
      metric: 'dailyChallengeStarted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_win_1_quiz',
      title: 'Passo doppio',
      description: 'Vinci 1 livello normale.',
      metric: 'normalQuizWon',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_check_daily_reward',
      title: 'Bonus sotto controllo',
      description: 'Apri la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_spin_wheel',
      title: 'Giro rituale',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_play_3_quiz',
      title: 'Buona rotta',
      description: 'Gioca 3 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'thu_daily_5_correct',
      title: 'Precisione lampo',
      description: 'Fai 5 risposte corrette nella sfida.',
      metric: 'dailyChallengeCorrect',
      target: 5,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'fri_spin_wheel',
      title: 'Ruota del venerdi',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_play_4_quiz',
      title: 'Precisione',
      description: 'Gioca 4 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 4,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_win_3_quiz',
      title: 'Tripletta',
      description: 'Vinci 3 livelli normali.',
      metric: 'normalQuizWon',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_check_daily_reward',
      title: 'Occhio al bonus',
      description: 'Controlla il daily reward.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_use_1_help',
      title: 'Venerdi brillante',
      description: 'Usa 1 aiuto in un livello normale.',
      metric: 'normalHelpsUsed',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'fri_daily_completed',
      title: 'Chiusura perfetta',
      description: 'Completa la sfida giornaliera.',
      metric: 'dailyChallengeCompleted',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'sat_play_3_quiz',
      title: 'Partenza sprint',
      description: 'Gioca 3 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 3,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_win_2_quiz',
      title: 'Sabato brillante',
      description: 'Vinci 2 livelli normali.',
      metric: 'normalQuizWon',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_check_daily_reward',
      title: 'Forziere quotidiano',
      description: 'Controlla la ricompensa giornaliera.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_use_2_helps',
      title: 'Ritmo weekend',
      description: 'Usa 2 aiuti nei livelli normali.',
      metric: 'normalHelpsUsed',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_spin_wheel',
      title: 'Colpo di fortuna',
      description: 'Gira la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sat_daily_8_correct',
      title: 'Sfida brillante',
      description: 'Fai 8 risposte corrette nella sfida giornaliera.',
      metric: 'dailyChallengeCorrect',
      target: 8,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
  [
    ADS_MISSION,
    {
      id: 'sun_play_2_quiz',
      title: 'Domenica easy',
      description: 'Gioca 2 livelli normali.',
      metric: 'normalQuizPlayed',
      target: 2,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_win_1_quiz',
      title: 'Colpo relax',
      description: 'Vinci 1 livello normale.',
      metric: 'normalQuizWon',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_check_daily_reward',
      title: 'Promemoria premio',
      description: 'Controlla se hai riscosso il daily.',
      metric: 'dailyRewardChecks',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_spin_wheel',
      title: 'Giro relax',
      description: 'Fai girare la ruota.',
      metric: 'wheelSpins',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_use_1_help',
      title: 'Gran finale',
      description: 'Usa 1 aiuto in un livello normale.',
      metric: 'normalHelpsUsed',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
    {
      id: 'sun_daily_no_help',
      title: 'Sfida pulita',
      description: 'Completa la sfida giornaliera senza aiuti.',
      metric: 'dailyChallengeNoHelp',
      target: 1,
      rewardCoins: DAILY_MISSION_REWARD_COINS,
    },
  ],
];

export const DAILY_MISSION_SWITCH_POOL: DailyMissionConfig[] = [
  {
    id: 'switch_check_daily_reward',
    title: 'Controllo bonus',
    description: 'Apri la reward giornaliera.',
    metric: 'dailyRewardChecks',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_spin_wheel',
    title: 'Giro di prova',
    description: 'Gira la ruota della fortuna.',
    metric: 'wheelSpins',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_play_2_quiz',
    title: 'Due partite',
    description: 'Gioca 2 livelli normali.',
    metric: 'normalQuizPlayed',
    target: 2,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_play_4_quiz',
    title: 'Quattro partite',
    description: 'Gioca 4 livelli normali.',
    metric: 'normalQuizPlayed',
    target: 4,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_win_1_quiz',
    title: 'Una vittoria',
    description: 'Vinci 1 livello normale.',
    metric: 'normalQuizWon',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_win_2_quiz',
    title: 'Due vittorie',
    description: 'Vinci 2 livelli normali.',
    metric: 'normalQuizWon',
    target: 2,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_use_1_help',
    title: 'Aiuto furbo',
    description: 'Usa 1 aiuto in un livello normale.',
    metric: 'normalHelpsUsed',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_use_2_helps',
    title: 'Doppia strategia',
    description: 'Usa 2 aiuti nei livelli normali.',
    metric: 'normalHelpsUsed',
    target: 2,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_complete_1_new_level',
    title: 'Nuovo livello',
    description: 'Completa 1 livello non ancora finito.',
    metric: 'normalLevelsCompleted',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_daily_started',
    title: 'Sfida avviata',
    description: 'Avvia la sfida giornaliera.',
    metric: 'dailyChallengeStarted',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_daily_5_correct',
    title: 'Cinque corrette',
    description: 'Rispondi correttamente a 5 domande della sfida.',
    metric: 'dailyChallengeCorrect',
    target: 5,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_daily_8_questions',
    title: 'Dentro la sfida',
    description: 'Gioca 8 domande nella sfida giornaliera.',
    metric: 'dailyChallengeQuestions',
    target: 8,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_daily_completed',
    title: 'Sfida completata',
    description: 'Completa la sfida giornaliera.',
    metric: 'dailyChallengeCompleted',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
  {
    id: 'switch_daily_no_help',
    title: 'Senza aiuti',
    description: 'Completa la sfida giornaliera senza aiuti.',
    metric: 'dailyChallengeNoHelp',
    target: 1,
    rewardCoins: DAILY_MISSION_REWARD_COINS,
  },
];

export const DAILY_WHEEL_REWARDS: DailyWheelRewardConfig[] = [
  {
    id: 'coins_3',
    label: '+3 TurtleCoins',
    shortLabel: '+3',
    type: 'coins',
    amount: 3,
    weight: 22,
  },
  {
    id: 'coins_5',
    label: '+5 TurtleCoins',
    shortLabel: '+5',
    type: 'coins',
    amount: 5,
    weight: 18,
  },
  {
    id: 'xp_10',
    label: '+10 XP',
    shortLabel: '+10 XP',
    type: 'xp',
    amount: 10,
    weight: 18,
  },
  {
    id: 'coins_8',
    label: '+8 TurtleCoins',
    shortLabel: '+8',
    type: 'coins',
    amount: 8,
    weight: 14,
  },
  {
    id: 'base_avatar',
    label: 'Avatar base',
    shortLabel: 'Avatar',
    type: 'baseAvatar',
    weight: 8,
  },
  {
    id: 'coins_10',
    label: '+10 TurtleCoins',
    shortLabel: '+10',
    type: 'coins',
    amount: 10,
    weight: 10,
  },
  {
    id: 'xp_5',
    label: '+5 XP',
    shortLabel: '+5 XP',
    type: 'xp',
    amount: 5,
    weight: 10,
  },
];

export const DAILY_EVENTS_CONFIG = {
  dailyChallengeQuestionCount: 10,
  dailyChallengeCoinsReward: 25,
  dailyChallengeDifficulty: 'easy' as DifficultyId,
};
